### ISSUE TITLE
Image Size Problem

### ISSUE THREAD

**Issue by dimaspratama08** [ultralytics/hub#502]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and [discussions](https://github.com/ultralytics/hub/discussions) and found no similar questions.

### Question

Hi everyone. I am trying to train a model from custom dataset which is aerial view of oil palm plantation. the image cover area about 30 ha with average 4000 objects. The dataset is in jpg format. I tried to train the model based on this data but i always got the following error:

train: Scanning /content/yolo_data/labels/train.cache... 0 images, 0 backgrounds, 1 corrupt: 100% 1/1 [00:00<?, ?it/s]
train: WARNING ⚠️ /content/yolo_data/images/train/JPG_OC23.jpg: ignoring corrupt image/label: Image size (334137060 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
WARNING ⚠️ No images found in /content/yolo_data/labels/train.cache, training may not work correctly. See https://docs.ultralytics.com/datasets/detect for dataset formatting guidance.
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/cfg/__init__.py", line 448, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/model.py", line 338, in train
    self.trainer.train()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 190, in train
    self._do_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 290, in _do_train
    self._setup_train(world_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/engine/trainer.py", line 259, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode='train')
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/train.py", line 46, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/models/yolo/detect/train.py", line 40, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == 'val', stride=gs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/build.py", line 80, in build_yolo_dataset
    return YOLODataset(
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/dataset.py", line 41, in __init__
    super().__init__(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/base.py", line 73, in __init__
    self.labels = self.get_labels()
  File "/usr/local/lib/python3.10/dist-packages/ultralytics/data/dataset.py", line 125, in get_labels
    len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
ValueError: not enough values to unpack (expected 3, got 0)

The first error message implied that i have corrupted image but when i check it's validity using opencv it return that my dataset are valid. The second error message implied that i have no label in my dataset but i used the ultralytics format. Please help me :(
![image](https://github.com/ultralytics/hub/assets/86192369/7fae8dca-8b9a-42b2-9b78-d72dd2290ece)
![image](https://github.com/ultralytics/hub/assets/86192369/839b6c9b-5c71-408d-b0c0-2bf453edbb18)
![image](https://github.com/ultralytics/hub/assets/86192369/8601d3b1-5cd8-40e6-bdea-ec2487078a64)
![image](https://github.com/ultralytics/hub/assets/86192369/328470bd-8fb4-4849-a5ea-bf316da18057)

**Comment by dimaspratama08** [comment]
@glenn-jocher

**Comment by kalenmike** [comment]
@dimaspratama08 Are you using Ultralytics HUB or the ultralytics pip package?

**Comment by dimaspratama08** [comment]
I tried both, they returned same error message

**Comment by UltralyticsAssistant** [comment]
Hello @dimaspratama08! The error indicating "Image size exceeds limit" suggests the images are too large for the model to process, likely exceeding memory capabilities due to the sheer number of pixels. To resolve this, you could try resizing your images to smaller dimensions that meet the model requirements. Make sure the resized images still preserve the necessary detail level for your objects to be detectable.

Regarding labels, please double-check that they are correctly formatted and associated with the right images. Also, ensure that label files (.txt) are in the correct directory and that no file is empty or corrupt.

Lastly, verify that paths in your dataset configuration file correctly point to your images and labels. The discrepancy between the actual files and paths specified in the configuration can lead to such errors.

If you are following all the correct steps and still face issues, consider reaching out at the Ultralytics HUB Docs for more detailed guidance on setting up your dataset and troubleshooting common problems.

**Comment by kalenmike** [comment]
@dimaspratama08 What happens when you use HUB? Does the dataset fail to process or are you able to upload the dataset but not able to train the model using the dataset?

**Comment by dimaspratama08** [comment]
@kalenmike i checked the dataset using check_dataset before uploading it, so i decided to crop the initial image and apparently it works, but now i have another problem, the predicted bounding box is too thick and it's hard for me to verify the result, is there a way to resize the predicted bounding box? im also using sahi for tiled inference
![image](https://github.com/ultralytics/hub/assets/86192369/0c6556f1-1538-40c8-ab5f-bb4975899620)

**Comment by kalenmike** [comment]
@dimaspratama08 You can use the line_width argument:

```bash
yolo predict source="path/to/img" line_width=1
```

**Comment by dimaspratama08** [comment]
@kalenmike Thanks! i have one last question, is it possible to transform the bounding box of predicted bbox into shapefile, and how? Below is the object_prediction_list provided by sahi.
![image](https://github.com/ultralytics/hub/assets/86192369/5b508cbf-2446-40a5-8724-f1b35512f193)

**Comment by pderrenger** [comment]
Hello @dimaspratama08! 🌟 Converting predicted bounding boxes to a shapefile format involves a few steps, but it's certainly doable. You'll need to iterate over your `object_prediction_list`, extract the bounding box coordinates, and then use a library like `geopandas` to create and save the shapefile. Here’s a brief outline of the process:

1. Install `geopandas` if you haven’t already.
2. Iterate through your `object_prediction_list`, extracting the relevant information (e.g., `minx`, `miny`, `maxx`, `maxy` for each bounding box).
3. For each bounding box, you can create a `Polygon` object using the coordinates.
4. Accumulate these `Polygon` objects along with any associated data into a list.
5. Use `geopandas.GeoDataFrame` to create a geodataframe from this list.
6. Finally, use `.to_file()` method of the geodataframe to save it as a shapefile.

Please note, the precise details may vary based on your exact requirements and data structure. The above steps should guide you towards achieving your goal of converting bounding boxes to a shapefile format. Good luck!
