### ISSUE TITLE
Model training not getting completed/ Disconnected. Stuck at 100%

### ISSUE THREAD

**Issue by Sudhir1609** [ultralytics/hub#952]
### Search before asking

- [X] I have searched the HUB [issues](https://github.com/ultralytics/hub/issues) and found no similar bug report.

### HUB Component

Models

### Bug

Its constantly getting stuck at 100% and not getting completed.

![Model12](https://github.com/user-attachments/assets/f2524ead-04c2-46e1-9f95-67f4e302cb42)

### Environment

Ultralytics HUB Version
v0.1.79
Client User Agent
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36
Operating System
Linux x86_64
Browser Window Size
1848 x 932
Server Timestamp
1734061093

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Sudhir1609, thank you for reporting an issue about [Ultralytics HUB](https://hub.ultralytics.com) 🚀! Please check out our [HUB Docs](https://docs.ultralytics.com/hub) for more information:

- [**Quickstart**](https://docs.ultralytics.com/hub/quickstart). Start training and deploying YOLO models with HUB in seconds.
- [**Datasets: Preparing and Uploading**](https://docs.ultralytics.com/hub/datasets). Learn how to prepare and upload your datasets to HUB in YOLO format.
- [**Projects: Creating and Managing**](https://docs.ultralytics.com/hub/projects). Group your models into projects for improved organization.
- [**Models: Training and Exporting**](https://docs.ultralytics.com/hub/models). Train YOLOv5 and YOLOv8 models on your custom datasets and export them to various formats for deployment.
- [**Integrations**](https://docs.ultralytics.com/hub/integrations). Explore different integration options for your trained models, such as TensorFlow, ONNX, OpenVINO, CoreML, and PaddlePaddle.
- [**Ultralytics HUB App**](https://docs.ultralytics.com/hub/app). Learn about the Ultralytics App for iOS and Android, which allows you to run models directly on your mobile device.
   * [**iOS**](https://docs.ultralytics.com/hub/app/ios). Learn about YOLO CoreML models accelerated on Apple's Neural Engine on iPhones and iPads.
   * [**Android**](https://docs.ultralytics.com/hub/app/android). Explore TFLite acceleration on mobile devices.
- [**Inference API**](https://docs.ultralytics.com/hub/inference-api). Understand how to use the Inference API for running your trained models in the cloud to generate predictions.

It looks like you've reported a 🐛 bug where the model gets stuck at 100% completion and doesn't finalize. To help us investigate and resolve this, could you please provide a **minimum reproducible example (MRE)**? This includes:

1. Detailed steps to reproduce the issue you're encountering.
2. Screenshots or relevant logs that might give us more context.
3. Information about any specific datasets, tasks, or customized configurations involved.

For guidance on creating an MRE, visit our [Minimum Reproducible Example guide](https://docs.ultralytics.com/help/minimum_reproducible_example/). 🛠️

An Ultralytics engineer will also review your issue and assist you shortly. Thank you for bringing this to our attention and for your patience! 😊

**Comment by sergiuwaxmann** [comment]
@Sudhir1609 Hello!
Can you share your model ID? You can find it on the URL of your model's page.

**Comment by Sudhir1609** [comment]
@sergiuwaxmann is this the correct URL ?
https://hub.ultralytics.com/models/dUv8hW4dgKL3dJu6TdaV

**Comment by sergiuwaxmann** [comment]
@Sudhir1609 Yes, this URL points to your model. I can see your model is disconnected and the last epoch is `95`.
You can try resuming the training while we investigate this issue further.

**Comment by Sudhir1609** [comment]
I've tried 'Resume Training' like 5-6 times now and everytime it gets disconnected around the same epoch, I'm worried losing my funds too.

**Comment by pderrenger** [comment]
Thank you for sharing the update, @Sudhir1609! I understand how frustrating this must be, especially with the concern about funds.

To address this, please try the following steps:

1. **Check Your Internet Stability**: Cloud training sessions can sometimes disconnect if there are interruptions in your network stability, so ensure you're on a reliable connection.
   
2. **Inspect the Logs**: From the model page, review the training logs to see if there's any specific error or indication of what's causing the disconnection.

3. **Resume Training**: Since the issue persists around the same epoch, try reducing your batch size or tweaking your dataset settings to see if that resolves any potential resource constraints. You can adjust these settings when resuming training.

4. **Funds and Billing**: Rest assured, the HUB deducts funds only for completed epochs. If the session disconnects before completing an epoch, the balance for that epoch should not be affected. You can verify this via the **Billing** tab in the HUB.

If the issue persists and you've already tried the above steps, please let us know. You can also share with us any specific error messages or logs that appear before the disconnection. We'll investigate further to ensure this gets resolved for you.

Thank you for your patience! 😊

**Comment by sergiuwaxmann** [comment]
@Sudhir1609 Unfortunately, the number of epochs can't be changed after the model started training.
Apologies for the inconvenience, we will refund the account balance you used so far for this training as we can see you tried resuming several times. Once we do this (you should see the account balance back in your account in about 30 minutes), maybe you can try creating a new model again and start a fresh training?

**Comment by Sudhir1609** [comment]
@sergiuwaxmann  Thanks, I was facing the same problem and tried the same steps for this model too.
https://hub.ultralytics.com/models/MD72j92nP9uX9fwShDIS

Thanks for you help !

**Comment by sergiuwaxmann** [comment]
@Sudhir1609 You should have your account balance back.
Maybe you can try choosing a different GPU? Which GPU did you use for the trainings that failed?

**Comment by sergiuwaxmann** [comment]
I believe the size of your dataset causes OOM issue but we are still investigating this.

**Comment by Sudhir1609** [comment]
@sergiuwaxmann I tried changing the instance between 
NVIDIA GeForce RTX 4090 and NVIDIA L40. 

Thanks for the update. I'll try to change my dataset and try again

**Comment by Sudhir1609** [comment]
@sergiuwaxmann I changed the dataset size and tired training the model and faced with the same problem
https://hub.ultralytics.com/models/zEDjZlwIbNiMnrD1qVtT

Can you please let me know about this

**Comment by yogendrasinghx** [comment]
@Sudhir1609 Thank you for your patience as we continue to investigate this issue. We're currently working to identify the root cause, but reproducing the problem has been challenging due to the large size of the dataset involved.

Please rest assured that we're actively working on this and will keep you updated as soon as we have more information. Apologies for the inconvenience, and thank you for your understanding! 🙏

**Comment by yogendrasinghx** [comment]
@Sudhir1609

Thank you for your patience and understanding as we looked into this issue. We have successfully reproduced the issue on our end and identified the root cause. The development team has been informed and is actively working on a fix.

We appreciate your cooperation and will update you as soon as the fix is deployed. 

Thank you! 😊

**Comment by Sudhir1609** [comment]
@yogendrasinghx 
Sure thanks for the update, Please let me know once the problem is fixed.
Hope I can train the model seamlessly soon

**Comment by Zablander** [comment]
I'm experiencing the same issue as reported in ticket number #1040. Has the problem been resolved, and what was the cause?

**Comment by pderrenger** [comment]
Thank you for reaching out! 🚀 We appreciate your patience while we investigate this training interruption issue. While I can't share specific details about internal ticket #1040, I can confirm our team has identified root causes related to **OOM (Out-of-Memory) challenges with large datasets** and is actively working on improvements. 

For optimal results while we finalize the fixes, we recommend:
1. Trying smaller subsets of your data with the [COCO128](https://docs.ultralytics.com/datasets/detect/coco/) dataset format as a test
2. Selecting GPUs with larger memory capacity (L40/4090 remain good choices)
3. Starting with conservative batch sizes

We'll update the [Ultralytics HUB Cloud Training documentation](https://docs.ultralytics.com/hub/cloud-training/) once enhancements are deployed. You can subscribe to notifications on the original [GitHub issue](https://github.com/ultralytics/hub/issues) for status updates.

For immediate needs, our [Model Training Tips guide](https://docs.ultralytics.com/guides/model-training-tips/) offers optimization strategies that might help stabilize your current training runs. Let us know if you encounter any new patterns we should investigate! 🔍

**Comment by Zablander** [comment]
I would like to request a refund for the account balance that has been used so far for this training: https://hub.ultralytics.com/projects/oiuCvp2vcZ0wiXixVIHw

45,50$

![Image](https://github.com/user-attachments/assets/23527950-37e5-42c3-ad04-5805e7d454c7)

**Comment by pderrenger** [comment]
Thank you for reaching out! We appreciate your patience as we review this request. For billing inquiries like refunds, please email our support team at **support @Zablander.com** with:  
1. Your project ID: `oiuCvp2vcZ0wiXixVIHw`  
2. A brief description of the issue  
3. The attached screenshot for reference  

Our team will investigate the training logs and process any eligible refunds per our [Cloud Training billing policy](https://docs.ultralytics.com/hub/cloud-training/#billing), which states:  
> *"The account balance is deducted after every epoch... If the session disconnects before completing an epoch, the balance for that epoch should not be affected."*  

While we resolve this, we recommend:  
- Verifying your dataset follows [YOLO format requirements](https://docs.ultralytics.com/datasets/detect/)  
- Using smaller subsets for testing (see [Training Tips](https://docs.ultralytics.com/guides/model-training-tips/#training-on-large-datasets))  
- Selecting GPUs with larger memory (L40/4090) for complex datasets  

You should receive a response within 24 business hours. Let us know if you need any other assistance! 🚀

**Comment by ANTHONYMETALFLANGER** [comment]
Probably the same issue, i tried to train yolo11s on the hand keypoints dataset (https://docs.ultralytics.com/ru/datasets/pose/hand-keypoints/). The model is trained on my hardware, in the server console after the last epoch I get a message that the finished model is loaded in the hub: 

> Speed: 0.1ms preprocess, 2.6ms inference, 0.0ms loss, 0.5ms postprocess per image
> Results saved to runs/pose/train2
> Ultralytics HUB: Syncing final model...
> 100%|██████████| 19.5M/19.5M [00:01<00:00, 11.9MB/s]
> Ultralytics HUB: Done 
> Ultralytics HUB: View model at https://hub.ultralytics.com/models/gZakA8v871qsfruVApnw

In the hub itself it says “0 epochs remaining” and also plots for all 100 epochs, but the status is “Disconnected. Checkpoint saved for epoch 11.”. It seems after some point checkpoints just stop being recorded for some unknown reason

![Image](https://github.com/user-attachments/assets/4eb1731c-22ea-40c6-bd1b-1f9d6bde99d2)

Preview and Deploy tabs are not available with the message “Model Not Trained!”. I didn't attach the entire output of the training script for all 100 epochs, it's quite long. I can only say that there was not a single traceback about loss of connection or anything like that and in general any errors on the side of my server did not seem to occur. When trying to run the training script on the server again, the training tries to start from epoch 11 but ends with traceback:

> Ultralytics HUB: New authentication successful ✅  
> Ultralytics HUB: View model at https://hub.ultralytics.com/models/gZakA8v871qsfruVApnw 
> Found https://storage.googleapis.com/ultralytics-hub.appspot.com/users/XMxHsmLiXfWigzc4Pp3jV3shn0C2/models/gZakA8v871qsfruVApnw/epoch-11.pt locally at weights/epoch-11.pt
> Traceback (most recent call last):
>   File "/home/paulo/sources/yolo11_hand_pose/train.py", line 6, in <module> 
>     model = YOLO('https://hub.ultralytics.com/models/gZakA8v871qsfruVApnw')
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/paulo/sources/yolo11_hand_pose/yolo11_hand_pose_env/lib64/python3/site-packages/ultralytics/models/yolo/model.py", line 23, in __init__
>     super().__init__(model=model, task=task, verbose=verbose)
>   File "/home/paulo/sources/yolo11_hand_pose/yolo11_hand_pose_env/lib64/python3/site-packages/ultralytics/engine/model.py", line 148, in __init__
>     self._load(model, task=task)
>   File "/home/paulo/sources/yolo11_hand_pose/yolo11_hand_pose_env/lib64/python3/site-packages/ultralytics/engine/model.py", line 290, in _load
>     self.model, self.ckpt = attempt_load_one_weight(weights)
>                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/paulo/sources/yolo11_hand_pose/yolo11_hand_pose_env/lib64/python3/site-packages/ultralytics/nn/tasks.py", line 1039, in attempt_load_one_weight
>     ckpt, weight = torch_safe_load(weight)  # load ckpt
>                    ^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/paulo/sources/yolo11_hand_pose/yolo11_hand_pose_env/lib64/python3/site-packages/ultralytics/nn/tasks.py", line 944, in torch_safe_load
>     ckpt = torch.load(file, map_location="cpu")
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/paulo/sources/yolo11_hand_pose/yolo11_hand_pose_env/lib64/python3/site-packages/ultralytics/utils/patches.py", line 86, in torch_load
>     return _torch_load(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/paulo/sources/yolo11_hand_pose/yolo11_hand_pose_env/lib64/python3/site-packages/torch/serialization.py", line 1495, in load
>     return _legacy_load(
>            ^^^^^^^^^^^^^
>   File "/home/paulo/sources/yolo11_hand_pose/yolo11_hand_pose_env/lib64/python3/site-packages/torch/serialization.py", line 1744, in _legacy_load
>     magic_number = pickle_module.load(f, **pickle_load_args)
>                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> _pickle.UnpicklingError: invalid load key, '<'.

I have tried creating a project and training a model before and encountered a similar problem, but there I was able to run the training again however the checkpoints still did not want to record beyond the point where they were stuck on

**Comment by pderrenger** [comment]
Thank you for the detailed report and for including the traceback! 🛠️ This appears to be a checkpoint syncing issue that we're actively investigating. Here's what we recommend:

1. **New Model Instance**: Since the existing checkpoint file (`epoch-11.pt`) appears corrupted (as indicated by the `UnpicklingError`), please create a fresh model in the Ultralytics HUB and start new training. You can use the same hand-keypoints dataset configuration from the [Ultralytics Hand Keypoints documentation](https://docs.ultralytics.com/datasets/pose/hand-keypoints/).

2. **Epoch Validation**: When starting fresh training, you might want to:
   ```python
   model.train(..., epochs=100, patience=50)  # Adjust patience relative to epochs
   ```
   This helps ensure completion even if some epochs take longer.

3. **Checkpoint Monitoring**: After starting new training, watch the [HUB Training Logs](https://docs.ultralytics.com/hub/models/#training-logs) in real-time to catch any mid-training sync issues.

4. **Network Stability**: Ensure stable internet connection during training, as checkpoints sync automatically after each epoch. Our [Cloud Training solution](https://docs.ultralytics.com/hub/cloud-training/) can help avoid local network issues.

We're working on improving checkpoint resilience in these edge cases. For immediate needs, the fresh training approach should unblock you. Let us know if the issue persists in new trainings, and we'll prioritize further investigation.

*Note: If you're using this for internal/proprietary purposes, please ensure compliance with our [AGPL-3.0 license](https://www.ultralytics.com/license) requirements.*
